window.readingQuestions = [
  { question: "What does the word 'reluctant' mean in the sentence: 'She was reluctant to leave the party'?", options: ["Unwilling", "Excited", "Quick", "Certain"], correct: 0 },
  { question: "Why did the author use the phrase 'a blanket of fog'?", options: ["To show the fog covered everything", "To describe a blanket", "To explain the weather", "To talk about warmth"], correct: 0 },
  { question: "Which word is closest in meaning to 'vivid'?", options: ["Bright", "Dull", "Quiet", "Rough"], correct: 0 },
  { question: "What is the main idea of a paragraph that describes a boy training for a race every morning?", options: ["He is determined", "He is lazy", "He is confused", "He is angry"], correct: 0 },
  { question: "Why might an author repeat a word or phrase?", options: ["To emphasize it", "To make the story longer", "To confuse the reader", "To introduce a new character"], correct: 0 },
  { question: "What does the word 'scampered' suggest about how the animal moved?", options: ["Quickly", "Slowly", "Loudly", "Carefully"], correct: 0 },
  { question: "If a character is described as 'timid', how do they probably act?", options: ["Shy", "Brave", "Angry", "Loud"], correct: 0 },
  { question: "What is the effect of using a question at the end of a paragraph?", options: ["Makes the reader think", "Ends the story", "Shows a character is confused", "Describes the setting"], correct: 0 },
  { question: "Which word is an antonym for 'ancient'?", options: ["Modern", "Old", "Historic", "Ruined"], correct: 0 },
  { question: "What does the phrase 'her heart leapt' suggest?", options: ["She was excited or surprised", "She was tired", "She was angry", "She was running"], correct: 0 },
  { question: "Why might an author use short sentences in a story?", options: ["To create tension", "To make it boring", "To describe a setting", "To introduce a character"], correct: 0 },
  { question: "What is the main purpose of a glossary in a book?", options: ["To define important words", "To list chapters", "To show the index", "To list the author's books"], correct: 0 },
  { question: "What does the word 'drenched' mean?", options: ["Soaked", "Dry", "Warm", "Cold"], correct: 0 },
  { question: "If a character 'sighed with relief', what does this show?", options: ["They were worried but now feel better", "They are angry", "They are tired", "They are excited"], correct: 0 },
  { question: "What is the effect of describing a setting as 'gloomy'?", options: ["Creates a sad or dark mood", "Shows it is sunny", "Shows it is busy", "Shows it is noisy"], correct: 0 },
  { question: "Which word is closest in meaning to 'eager'?", options: ["Keen", "Lazy", "Sad", "Tired"], correct: 0 },
  { question: "Why might an author use dialogue in a story?", options: ["To show what characters say", "To describe the setting", "To explain the plot", "To list events"], correct: 0 },
  { question: "What does the word 'stumbled' suggest about how someone moved?", options: ["Unsteadily", "Quickly", "Gracefully", "Quietly"], correct: 0 },
  { question: "If a character is 'determined', what are they likely to do?", options: ["Keep trying", "Give up", "Complain", "Forget"], correct: 0 },
  { question: "What is the main idea of a paragraph about a girl practicing piano every day?", options: ["She is hardworking", "She is bored", "She is confused", "She is angry"], correct: 0 },
  { question: "Why might an author use a simile?", options: ["To compare things", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'vanished' mean?", options: ["Disappeared", "Appeared", "Changed", "Arrived"], correct: 0 },
  { question: "If a character 'beamed with pride', what does this show?", options: ["They are proud", "They are sad", "They are tired", "They are angry"], correct: 0 },
  { question: "What is the effect of describing a character as 'mysterious'?", options: ["Creates curiosity", "Shows they are funny", "Shows they are loud", "Shows they are tired"], correct: 0 },
  { question: "Which word is an antonym for 'generous'?", options: ["Selfish", "Kind", "Helpful", "Caring"], correct: 0 },
  { question: "What does the phrase 'her eyes sparkled' suggest?", options: ["She is happy or excited", "She is tired", "She is angry", "She is confused"], correct: 0 },
  { question: "Why might an author use a cliffhanger at the end of a chapter?", options: ["To make the reader want to read more", "To end the story", "To introduce a new character", "To describe the setting"], correct: 0 },
  { question: "What does the word 'hesitated' mean?", options: ["Paused before acting", "Ran quickly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character is 'resourceful', what does this mean?", options: ["Good at solving problems", "Lazy", "Forgetful", "Angry"], correct: 0 },
  { question: "What is the main idea of a paragraph about a boy helping his friend with homework?", options: ["He is helpful", "He is bored", "He is confused", "He is angry"], correct: 0 },
  { question: "Why might an author use repetition?", options: ["To emphasize something", "To make the story longer", "To confuse the reader", "To introduce a new character"], correct: 0 },
  { question: "What does the word 'gazed' mean?", options: ["Looked steadily", "Shouted", "Ran", "Jumped"], correct: 0 },
  { question: "If a character 'shrugged', what does this show?", options: ["They are unsure or don't care", "They are angry", "They are excited", "They are tired"], correct: 0 },
  { question: "What is the effect of describing a setting as 'bustling'?", options: ["Shows it is busy", "Shows it is quiet", "Shows it is dark", "Shows it is empty"], correct: 0 },
  { question: "Which word is closest in meaning to 'cautious'?", options: ["Careful", "Quick", "Loud", "Brave"], correct: 0 },
  { question: "Why might an author use a metaphor?", options: ["To create a vivid image", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'lurking' suggest?", options: ["Hiding", "Running", "Jumping", "Shouting"], correct: 0 },
  { question: "If a character is 'optimistic', how do they probably feel?", options: ["Hopeful", "Sad", "Angry", "Tired"], correct: 0 },
  { question: "What is the main idea of a paragraph about a girl reading every night?", options: ["She enjoys reading", "She is bored", "She is confused", "She is angry"], correct: 0 },
  { question: "Why might an author use alliteration?", options: ["To create rhythm or mood", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'scurried' mean?", options: ["Moved quickly", "Moved slowly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character 'frowned', what does this show?", options: ["They are unhappy or thinking", "They are excited", "They are tired", "They are confused"], correct: 0 },
  { question: "What is the effect of describing a character as 'confident'?", options: ["Shows they believe in themselves", "Shows they are shy", "Shows they are tired", "Shows they are angry"], correct: 0 },
  { question: "Which word is an antonym for 'brave'?", options: ["Cowardly", "Strong", "Bold", "Fearless"], correct: 0 },
  { question: "What does the phrase 'his voice trembled' suggest?", options: ["He is nervous or scared", "He is excited", "He is angry", "He is tired"], correct: 0 },
  { question: "Why might an author use a rhetorical question?", options: ["To make the reader think", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'dawdled' mean?", options: ["Moved slowly", "Moved quickly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character is 'persistent', what are they likely to do?", options: ["Keep trying", "Give up", "Complain", "Forget"], correct: 0 },
  { question: "What is the main idea of a paragraph about a boy building a model airplane?", options: ["He is creative", "He is bored", "He is confused", "He is angry"], correct: 0 },
  { question: "Why might an author use personification?", options: ["To give human qualities to non-humans", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'ambled' mean?", options: ["Walked slowly", "Ran quickly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character 'grinned', what does this show?", options: ["They are happy or amused", "They are sad", "They are tired", "They are angry"], correct: 0 },
  { question: "What is the effect of describing a setting as 'serene'?", options: ["Shows it is calm and peaceful", "Shows it is busy", "Shows it is dark", "Shows it is noisy"], correct: 0 },
  { question: "Which word is closest in meaning to 'furious'?", options: ["Angry", "Happy", "Tired", "Calm"], correct: 0 },
  { question: "Why might an author use onomatopoeia?", options: ["To imitate sounds", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'peered' mean?", options: ["Looked closely", "Shouted", "Ran", "Jumped"], correct: 0 },
  { question: "If a character 'shrieked', what does this show?", options: ["They are scared or surprised", "They are happy", "They are tired", "They are angry"], correct: 0 },
  { question: "What is the effect of describing a character as 'generous'?", options: ["Shows they are kind and giving", "Shows they are selfish", "Shows they are tired", "Shows they are angry"], correct: 0 },
  { question: "Which word is an antonym for 'scarce'?", options: ["Plentiful", "Rare", "Limited", "Few"], correct: 0 },
  { question: "What does the phrase 'her hands trembled' suggest?", options: ["She is nervous or scared", "She is excited", "She is angry", "She is tired"], correct: 0 },
  { question: "Why might an author use a flashback?", options: ["To show something that happened earlier", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'bolted' mean?", options: ["Ran quickly", "Walked slowly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character is 'sceptical', how do they probably feel?", options: ["Doubtful", "Hopeful", "Angry", "Tired"], correct: 0 },
  { question: "What is the main idea of a paragraph about a girl helping her brother with homework?", options: ["She is helpful", "She is bored", "She is confused", "She is angry"], correct: 0 },
  { question: "Why might an author use foreshadowing?", options: ["To hint at future events", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'meandered' mean?", options: ["Wandered without direction", "Ran quickly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character 'winced', what does this show?", options: ["They are in pain or discomfort", "They are happy", "They are tired", "They are angry"], correct: 0 },
  { question: "What is the effect of describing a setting as 'bleak'?", options: ["Shows it is cold and unwelcoming", "Shows it is sunny", "Shows it is busy", "Shows it is noisy"], correct: 0 },
  { question: "Which word is closest in meaning to 'elated'?", options: ["Very happy", "Sad", "Tired", "Calm"], correct: 0 },
  { question: "Why might an author use hyperbole?", options: ["To exaggerate for effect", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'muttered' mean?", options: ["Spoke quietly", "Shouted", "Ran", "Jumped"], correct: 0 },
  { question: "If a character 'scowled', what does this show?", options: ["They are angry or displeased", "They are happy", "They are tired", "They are confused"], correct: 0 },
  { question: "What does the word 'yearned' mean?", options: ["Longed for", "Forgot", "Feared", "Ignored"], correct: 0 },
  { question: "Why might an author use a first-person narrator?", options: ["To show the story from the character's perspective", "To describe the setting", "To explain the plot", "To list events"], correct: 0 },
  { question: "Which word is an antonym for 'scarce'?", options: ["Abundant", "Rare", "Limited", "Few"], correct: 0 },
  { question: "What does the phrase 'his face fell' suggest?", options: ["He was disappointed", "He was happy", "He was angry", "He was tired"], correct: 0 },
  { question: "If a character is 'meticulous', how do they probably act?", options: ["Carefully", "Quickly", "Lazily", "Loudly"], correct: 0 },
  { question: "What is the effect of describing a setting as 'picturesque'?", options: ["Shows it is beautiful", "Shows it is dark", "Shows it is noisy", "Shows it is busy"], correct: 0 },
  { question: "Which word is closest in meaning to 'dismal'?", options: ["Gloomy", "Bright", "Noisy", "Busy"], correct: 0 },
  { question: "Why might an author use a third-person narrator?", options: ["To show the story from outside the characters", "To describe the setting", "To explain the plot", "To list events"], correct: 0 },
  { question: "What does the word 'beckoned' mean?", options: ["Signaled to come", "Shouted", "Ran", "Jumped"], correct: 0 },
  { question: "If a character 'gasped', what does this show?", options: ["They are surprised or shocked", "They are happy", "They are tired", "They are angry"], correct: 0 },
  { question: "What is the effect of describing a character as 'aloof'?", options: ["Shows they are distant or unfriendly", "Shows they are kind", "Shows they are tired", "Shows they are angry"], correct: 0 },
  { question: "Which word is an antonym for 'expand'?", options: ["Contract", "Grow", "Increase", "Enlarge"], correct: 0 },
  { question: "What does the phrase 'her voice was barely a whisper' suggest?", options: ["She spoke very quietly", "She shouted", "She sang", "She laughed"], correct: 0 },
  { question: "Why might an author use a flash-forward?", options: ["To show future events", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'ambled' mean?", options: ["Walked slowly", "Ran quickly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character 'glared', what does this show?", options: ["They are angry or annoyed", "They are happy", "They are tired", "They are confused"], correct: 0 },
  { question: "What is the effect of describing a setting as 'dreary'?", options: ["Shows it is dull and depressing", "Shows it is bright", "Shows it is noisy", "Shows it is busy"], correct: 0 },
  { question: "Which word is closest in meaning to 'content'?", options: ["Satisfied", "Sad", "Angry", "Tired"], correct: 0 },
  { question: "Why might an author use a prologue?", options: ["To introduce background information", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'bellowed' mean?", options: ["Shouted loudly", "Whispered", "Ran", "Jumped"], correct: 0 },
  { question: "If a character 'quivered', what does this show?", options: ["They are nervous or scared", "They are happy", "They are tired", "They are angry"], correct: 0 },
  { question: "What is the effect of describing a character as 'charismatic'?", options: ["Shows they attract others", "Shows they are shy", "Shows they are tired", "Shows they are angry"], correct: 0 },
  { question: "Which word is an antonym for 'scarce'?", options: ["Plentiful", "Rare", "Limited", "Few"], correct: 0 },
  { question: "What does the phrase 'his heart sank' suggest?", options: ["He was disappointed", "He was happy", "He was angry", "He was tired"], correct: 0 },
  { question: "Why might an author use a subplot?", options: ["To add depth to the story", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'sauntered' mean?", options: ["Walked in a relaxed way", "Ran quickly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character 'grimaced', what does this show?", options: ["They are in pain or disgusted", "They are happy", "They are tired", "They are angry"], correct: 0 },
  { question: "What is the effect of describing a setting as 'enchanting'?", options: ["Shows it is magical or charming", "Shows it is dark", "Shows it is noisy", "Shows it is busy"], correct: 0 },
  { question: "Which word is closest in meaning to 'melancholy'?", options: ["Sad", "Happy", "Tired", "Calm"], correct: 0 },
  { question: "Why might an author use a twist ending?", options: ["To surprise the reader", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'murmured' mean?", options: ["Spoke softly", "Shouted", "Ran", "Jumped"], correct: 0 },
  { question: "If a character 'beamed', what does this show?", options: ["They are happy or proud", "They are sad", "They are tired", "They are angry"], correct: 0 },
  { question: "What is the effect of describing a character as 'timid'?", options: ["Shows they are shy or nervous", "Shows they are bold", "Shows they are tired", "Shows they are angry"], correct: 0 },
  { question: "Which word is an antonym for 'abundant'?", options: ["Scarce", "Plentiful", "Many", "Numerous"], correct: 0 },
  { question: "What does the phrase 'her eyes widened' suggest?", options: ["She was surprised or shocked", "She was tired", "She was angry", "She was confused"], correct: 0 },
  { question: "Why might an author use a motif?", options: ["To reinforce a theme", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'darted' mean?", options: ["Moved quickly", "Moved slowly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character 'sighed', what does this show?", options: ["They are relieved or tired", "They are happy", "They are angry", "They are excited"], correct: 0 },
  { question: "What is the effect of describing a setting as 'oppressive'?", options: ["Shows it is uncomfortable or stifling", "Shows it is bright", "Shows it is noisy", "Shows it is busy"], correct: 0 },
  { question: "Which word is closest in meaning to 'exuberant'?", options: ["Full of energy", "Sad", "Tired", "Calm"], correct: 0 },
  { question: "Why might an author use a flashback?", options: ["To show something that happened earlier", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'ambled' mean?", options: ["Walked slowly", "Ran quickly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character 'scowled', what does this show?", options: ["They are angry or displeased", "They are happy", "They are tired", "They are confused"], correct: 0 },
  { question: "What is the effect of describing a character as 'generous'?", options: ["Shows they are kind and giving", "Shows they are selfish", "Shows they are tired", "Shows they are angry"], correct: 0 },
  { question: "Which word is an antonym for 'scarce'?", options: ["Plentiful", "Rare", "Limited", "Few"], correct: 0 },
  { question: "What does the phrase 'her hands trembled' suggest?", options: ["She is nervous or scared", "She is excited", "She is angry", "She is tired"], correct: 0 },
  { question: "Why might an author use a flashback?", options: ["To show something that happened earlier", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'bolted' mean?", options: ["Ran quickly", "Walked slowly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character is 'sceptical', how do they probably feel?", options: ["Doubtful", "Hopeful", "Angry", "Tired"], correct: 0 },
  { question: "What is the main idea of a paragraph about a girl helping her brother with homework?", options: ["She is helpful", "She is bored", "She is confused", "She is angry"], correct: 0 },
  { question: "Why might an author use foreshadowing?", options: ["To hint at future events", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'meandered' mean?", options: ["Wandered without direction", "Ran quickly", "Shouted", "Laughed"], correct: 0 },
  { question: "If a character 'winced', what does this show?", options: ["They are in pain or discomfort", "They are happy", "They are tired", "They are angry"], correct: 0 },
  { question: "What is the effect of describing a setting as 'bleak'?", options: ["Shows it is cold and unwelcoming", "Shows it is sunny", "Shows it is busy", "Shows it is noisy"], correct: 0 },
  { question: "Which word is closest in meaning to 'elated'?", options: ["Very happy", "Sad", "Tired", "Calm"], correct: 0 },
  { question: "Why might an author use hyperbole?", options: ["To exaggerate for effect", "To describe a character", "To explain a plot", "To list events"], correct: 0 },
  { question: "What does the word 'muttered' mean?", options: ["Spoke quietly", "Shouted", "Ran", "Jumped"], correct: 0 },
  { question: "If a character 'scowled', what does this show?", options: ["They are angry or displeased", "They are happy", "They are tired", "They are confused"], correct: 0 }
];