window.spagQuestions = [
  { question: "Correct the spelling: The adventurer was determind to conquer the mountain's peak.", options: ["determined", "determin", "determaned", "deturmined"], correct: 0 },
  { question: "Add correct punctuation: However the journey was perilous Elara pressed on", options: ["However, the journey was perilous; Elara pressed on.", "However the journey was perilous Elara pressed on.", "However, the journey was perilous Elara pressed on.", "However the journey was perilous; Elara pressed on."], correct: 0 },
  { question: "Rewrite in passive voice: The sorcerer cast a powerful spell.", options: ["A powerful spell was cast by the sorcerer.", "The sorcerer was cast by a powerful spell.", "A powerful spell cast the sorcerer.", "The sorcerer casted a powerful spell."], correct: 0 },
  { question: "Which is a noun?", options: ["Dog", "Run", "Quickly", "Blue"], correct: 0 },
  { question: "Which is a verb?", options: ["Jump", "Cat", "Red", "Soft"], correct: 0 },
  { question: "Which is an adjective?", options: ["Happy", "Run", "Dog", "Swim"], correct: 0 },
  { question: "Which is an adverb?", options: ["Quickly", "Cat", "Blue", "Eat"], correct: 0 },
  { question: "What is the plural of 'child'?", options: ["Children", "Childs", "Childes", "Childrens"], correct: 0 },
  { question: "Which sentence is correct?", options: ["She is running.", "She running is.", "Running she is.", "Is she running."], correct: 0 },
  { question: "Which word is a pronoun?", options: ["He", "Dog", "Run", "Blue"], correct: 0 },
  { question: "Which is a conjunction?", options: ["And", "Dog", "Run", "Blue"], correct: 0 },
  { question: "Which is a preposition?", options: ["Under", "Dog", "Run", "Blue"], correct: 0 },
  { question: "Which is an interjection?", options: ["Wow!", "Dog", "Run", "Blue"], correct: 0 },
  { question: "Choose the correct homophone: Their/There/They're going to the park.", options: ["They're", "Their", "There", "Thare"], correct: 0 },
  { question: "Which sentence uses a colon correctly?", options: ["He brought three things: a torch, a map, and a compass.", "He: brought three things a torch, a map, and a compass.", "He brought: three things a torch, a map, and a compass.", "He brought three things a torch, a map, and a compass:"], correct: 0 },
  { question: "Which is a synonym for 'brave'?", options: ["Courageous", "Cowardly", "Timid", "Lazy"], correct: 0 },
  { question: "Which is an antonym for 'generous'?", options: ["Selfish", "Kind", "Helpful", "Caring"], correct: 0 },
  { question: "Which sentence is in the present perfect tense?", options: ["She has finished her homework.", "She finished her homework.", "She is finishing her homework.", "She will finish her homework."], correct: 0 },
  { question: "Which is a subordinating conjunction?", options: ["Although", "And", "Or", "But"], correct: 0 },
  { question: "Which is a main clause?", options: ["The dog barked", "Because it was loud", "When it rained", "If you go"], correct: 0 },
  { question: "Which is a relative pronoun?", options: ["Who", "And", "But", "Quickly"], correct: 0 },
  { question: "Which is a fronted adverbial?", options: ["Before sunrise,", "The cat slept.", "He ran quickly.", "She is tired."], correct: 0 },
  { question: "Which sentence uses an apostrophe for possession?", options: ["The girl's book", "The girls book", "The girls' book", "The girl book"], correct: 0 },
  { question: "Which is a modal verb?", options: ["Could", "Run", "Dog", "Blue"], correct: 0 },
  { question: "Which is a determiner?", options: ["Some", "Quickly", "Run", "Blue"], correct: 0 },
  { question: "Which is a proper noun?", options: ["London", "city", "building", "street"], correct: 0 },
  { question: "Which is a question tag?", options: ["isn't it?", "quickly", "run", "blue"], correct: 0 },
  { question: "Which is a synonym for 'happy'?", options: ["Joyful", "Sad", "Angry", "Tired"], correct: 0 },
  { question: "Which is an antonym for 'ancient'?", options: ["Modern", "Old", "Historic", "Ruined"], correct: 0 },
  { question: "Which sentence uses a semicolon correctly?", options: ["It was late; we went home.", "It was; late we went home.", "It; was late we went home.", "It was late we went; home."], correct: 0 },
  { question: "Which is a collective noun?", options: ["Flock", "Dog", "Run", "Blue"], correct: 0 },
  { question: "Which is a possessive pronoun?", options: ["Mine", "Me", "I", "He"], correct: 0 },
  { question: "Which is a synonym for 'quick'?", options: ["Fast", "Slow", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'difficult'?", options: ["Easy", "Hard", "Tough", "Challenging"], correct: 0 },
  { question: "Which sentence is in the passive voice?", options: ["The cake was eaten by the children.", "The children ate the cake.", "The children are eating the cake.", "The children will eat the cake."], correct: 0 },
  { question: "Which is a plural noun?", options: ["Cats", "Cat", "Dog", "Blue"], correct: 0 },
  { question: "Which is a compound sentence?", options: ["She was tired, but she finished her work.", "She was tired because she finished her work.", "She was tired after she finished her work.", "She was tired when she finished her work."], correct: 0 },
  { question: "Which is a synonym for 'silent'?", options: ["Quiet", "Loud", "Noisy", "Busy"], correct: 0 },
  { question: "Which is an antonym for 'brave'?", options: ["Cowardly", "Strong", "Bold", "Fearless"], correct: 0 },
  { question: "Which sentence uses a comma for a list?", options: ["I bought apples, oranges, and bananas.", "I bought apples oranges and bananas.", "I bought apples and oranges and bananas.", "I bought apples, oranges and bananas."], correct: 0 },
  { question: "Which is a verb in the past tense?", options: ["Jumped", "Jump", "Jumping", "Jumps"], correct: 0 },
  { question: "Which is a synonym for 'angry'?", options: ["Furious", "Happy", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'scarce'?", options: ["Plentiful", "Rare", "Limited", "Few"], correct: 0 },
  { question: "Which sentence uses a dash correctly?", options: ["He was late – again.", "He was – late again.", "He – was late again.", "He was late again –."], correct: 0 },
  { question: "Which is a preposition of place?", options: ["Under", "Quickly", "Run", "Blue"], correct: 0 },
  { question: "Which is a synonym for 'tired'?", options: ["Weary", "Happy", "Angry", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'strong'?", options: ["Weak", "Tough", "Brave", "Bold"], correct: 0 },
  { question: "Which sentence uses a question mark correctly?", options: ["Are you coming?", "Are you coming.", "Are you coming!", "Are you coming,"], correct: 0 },
  { question: "Which is a verb in the present continuous tense?", options: ["Running", "Run", "Ran", "Runs"], correct: 0 },
  { question: "Which is a synonym for 'sad'?", options: ["Unhappy", "Happy", "Angry", "Tired"], correct: 0 },
  { question: "Which is an antonym for 'noisy'?", options: ["Quiet", "Loud", "Busy", "Calm"], correct: 0 },
  { question: "Which sentence uses an exclamation mark correctly?", options: ["Watch out!", "Watch out.", "Watch out?", "Watch out,"], correct: 0 },
  { question: "Which is a verb in the future tense?", options: ["Will run", "Ran", "Running", "Runs"], correct: 0 },
  { question: "Which is a synonym for 'calm'?", options: ["Peaceful", "Loud", "Busy", "Noisy"], correct: 0 },
  { question: "Which is an antonym for 'happy'?", options: ["Sad", "Joyful", "Excited", "Glad"], correct: 0 },
  { question: "Which sentence uses a full stop correctly?", options: ["She went home.", "She went home!", "She went home?", "She went home,"], correct: 0 },
  { question: "Which is a verb in the present simple tense?", options: ["Runs", "Run", "Running", "Ran"], correct: 0 },
  { question: "Which is a synonym for 'small'?", options: ["Tiny", "Big", "Large", "Huge"], correct: 0 },
  { question: "Which is an antonym for 'fast'?", options: ["Slow", "Quick", "Speedy", "Swift"], correct: 0 },
  { question: "Which sentence uses a capital letter correctly?", options: ["London is a city.", "london is a city.", "London Is a city.", "london Is a city."], correct: 0 },
  { question: "Which is a verb in the past perfect tense?", options: ["Had run", "Run", "Running", "Runs"], correct: 0 },
  { question: "Which is a synonym for 'difficult'?", options: ["Challenging", "Easy", "Simple", "Quick"], correct: 0 },
  { question: "Which is an antonym for 'thick'?", options: ["Thin", "Wide", "Broad", "Large"], correct: 0 },
  { question: "Which sentence uses a colon correctly?", options: ["She had three pets: a cat, a dog, and a rabbit.", "She had: three pets a cat, a dog, and a rabbit.", "She had three pets a cat, a dog, and a rabbit:", "She had three pets: a cat a dog and a rabbit."], correct: 0 },
  { question: "Which is a verb in the present perfect tense?", options: ["Has run", "Run", "Running", "Runs"], correct: 0 },
  { question: "Which is a synonym for 'strong'?", options: ["Powerful", "Weak", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'deep'?", options: ["Shallow", "Wide", "Narrow", "Long"], correct: 0 },
  { question: "Which sentence uses a semicolon correctly?", options: ["She was tired; she went to bed.", "She was; tired she went to bed.", "She; was tired she went to bed.", "She was tired she went; to bed."], correct: 0 },
  { question: "Which is a verb in the past continuous tense?", options: ["Was running", "Run", "Running", "Runs"], correct: 0 },
  { question: "Which is a synonym for 'loud'?", options: ["Noisy", "Quiet", "Calm", "Peaceful"], correct: 0 },
  { question: "Which is an antonym for 'wide'?", options: ["Narrow", "Broad", "Large", "Big"], correct: 0 },
  { question: "Which sentence uses a dash correctly?", options: ["She was happy – she smiled.", "She was – happy she smiled.", "She – was happy she smiled.", "She was happy she smiled –."], correct: 0 },
  { question: "Which is a verb in the future perfect tense?", options: ["Will have run", "Run", "Running", "Runs"], correct: 0 },
  { question: "Which is a synonym for 'angry'?", options: ["Irate", "Happy", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'empty'?", options: ["Full", "Hollow", "Vacant", "Bare"], correct: 0 },
  { question: "Which sentence uses a comma for a list?", options: ["She bought apples, oranges, and bananas.", "She bought apples oranges and bananas.", "She bought apples and oranges and bananas.", "She bought apples, oranges and bananas."], correct: 0 },
  { question: "Which is a verb in the present continuous tense?", options: ["Is running", "Ran", "Runs", "Run"], correct: 0 },
  { question: "Which is a synonym for 'brave'?", options: ["Valiant", "Cowardly", "Timid", "Lazy"], correct: 0 },
  { question: "Which is an antonym for 'polite'?", options: ["Rude", "Kind", "Helpful", "Caring"], correct: 0 },
  { question: "Which sentence is in the past perfect tense?", options: ["She had finished her homework.", "She finished her homework.", "She is finishing her homework.", "She will finish her homework."], correct: 0 },
  { question: "Which is a coordinating conjunction?", options: ["But", "Although", "Because", "If"], correct: 0 },
  { question: "Which is a subordinate clause?", options: ["Because it was raining", "The dog barked", "She ran quickly", "He is tired"], correct: 0 },
  { question: "Which is a relative clause?", options: ["Who was late", "And then", "But she", "Quickly"], correct: 0 },
  { question: "Which is a fronted adverbial?", options: ["After lunch,", "The dog barked.", "He ran quickly.", "She is tired."], correct: 0 },
  { question: "Which sentence uses an apostrophe for omission?", options: ["Don't go outside.", "The dogs bone.", "The dogs' bone.", "The dog bone."], correct: 0 },
  { question: "Which is a modal verb?", options: ["Should", "Run", "Dog", "Blue"], correct: 0 },
  { question: "Which is a determiner?", options: ["Many", "Quickly", "Run", "Blue"], correct: 0 },
  { question: "Which is a proper noun?", options: ["Paris", "city", "building", "street"], correct: 0 },
  { question: "Which is a question tag?", options: ["aren't you?", "quickly", "run", "blue"], correct: 0 },
  { question: "Which is a synonym for 'sad'?", options: ["Miserable", "Happy", "Angry", "Tired"], correct: 0 },
  { question: "Which is an antonym for 'strong'?", options: ["Weak", "Tough", "Brave", "Bold"], correct: 0 },
  { question: "Which sentence uses a colon correctly?", options: ["He had one wish: to be happy.", "He: had one wish to be happy.", "He had one wish to be happy:", "He had one wish: to be happy"], correct: 0 },
  { question: "Which is a collective noun?", options: ["Team", "Dog", "Run", "Blue"], correct: 0 },
  { question: "Which is a possessive pronoun?", options: ["Yours", "You", "He", "She"], correct: 0 },
  { question: "Which is a synonym for 'fast'?", options: ["Rapid", "Slow", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'difficult'?", options: ["Simple", "Hard", "Tough", "Challenging"], correct: 0 },
  { question: "Which sentence is in the passive voice?", options: ["The ball was thrown by Sam.", "Sam threw the ball.", "Sam is throwing the ball.", "Sam will throw the ball."], correct: 0 },
  { question: "Which is a plural noun?", options: ["Dogs", "Dog", "Cat", "Blue"], correct: 0 },
  { question: "Which is a compound sentence?", options: ["She was cold, so she wore a coat.", "She was cold because she wore a coat.", "She was cold after she wore a coat.", "She was cold when she wore a coat."], correct: 0 },
  { question: "Which is a synonym for 'quiet'?", options: ["Silent", "Loud", "Noisy", "Busy"], correct: 0 },
  { question: "Which is an antonym for 'brave'?", options: ["Fearful", "Strong", "Bold", "Fearless"], correct: 0 },
  { question: "Which sentence uses a comma for a list?", options: ["He bought bread, milk, and eggs.", "He bought bread milk and eggs.", "He bought bread and milk and eggs.", "He bought bread, milk and eggs."], correct: 0 },
  { question: "Which is a verb in the past tense?", options: ["Walked", "Walk", "Walking", "Walks"], correct: 0 },
  { question: "Which is a synonym for 'angry'?", options: ["Enraged", "Happy", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'scarce'?", options: ["Abundant", "Rare", "Limited", "Few"], correct: 0 },
  { question: "Which sentence uses a dash correctly?", options: ["It was cold – she wore a scarf.", "It was – cold she wore a scarf.", "It – was cold she wore a scarf.", "It was cold she wore a scarf –."], correct: 0 },
  { question: "Which is a preposition of time?", options: ["Before", "Quickly", "Run", "Blue"], correct: 0 },
  { question: "Which is a synonym for 'tired'?", options: ["Exhausted", "Happy", "Angry", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'strong'?", options: ["Feeble", "Tough", "Brave", "Bold"], correct: 0 },
  { question: "Which sentence uses a question mark correctly?", options: ["Did you see that?", "Did you see that.", "Did you see that!", "Did you see that,"], correct: 0 },
  { question: "Which is a verb in the present continuous tense?", options: ["Is eating", "Eat", "Ate", "Eats"], correct: 0 },
  { question: "Which is a synonym for 'happy'?", options: ["Content", "Sad", "Angry", "Tired"], correct: 0 },
  { question: "Which is an antonym for 'noisy'?", options: ["Peaceful", "Loud", "Busy", "Calm"], correct: 0 },
  { question: "Which sentence uses an exclamation mark correctly?", options: ["Look out!", "Look out.", "Look out?", "Look out,"], correct: 0 },
  { question: "Which is a verb in the future tense?", options: ["Will eat", "Eat", "Ate", "Eats"], correct: 0 },
  { question: "Which is a synonym for 'calm'?", options: ["Tranquil", "Loud", "Busy", "Noisy"], correct: 0 },
  { question: "Which is an antonym for 'happy'?", options: ["Miserable", "Joyful", "Excited", "Glad"], correct: 0 },
  { question: "Which sentence uses a full stop correctly?", options: ["He went home.", "He went home!", "He went home?", "He went home,"], correct: 0 },
  { question: "Which is a verb in the present simple tense?", options: ["Eats", "Eat", "Eating", "Ate"], correct: 0 },
  { question: "Which is a synonym for 'small'?", options: ["Petite", "Big", "Large", "Huge"], correct: 0 },
  { question: "Which is an antonym for 'fast'?", options: ["Sluggish", "Quick", "Speedy", "Swift"], correct: 0 },
  { question: "Which sentence uses a capital letter correctly?", options: ["Paris is in France.", "paris is in France.", "Paris Is in France.", "paris Is in France."], correct: 0 },
  { question: "Which is a verb in the past perfect tense?", options: ["Had eaten", "Eat", "Eating", "Eats"], correct: 0 },
  { question: "Which is a synonym for 'difficult'?", options: ["Arduous", "Easy", "Simple", "Quick"], correct: 0 },
  { question: "Which is an antonym for 'thick'?", options: ["Slim", "Wide", "Broad", "Large"], correct: 0 },
  { question: "Which sentence uses a colon correctly?", options: ["He had one goal: to win.", "He: had one goal to win.", "He had one goal to win:", "He had one goal: to win"], correct: 0 },
  { question: "Which is a verb in the present perfect tense?", options: ["Has eaten", "Eat", "Eating", "Eats"], correct: 0 },
  { question: "Which is a synonym for 'strong'?", options: ["Sturdy", "Weak", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'deep'?", options: ["Superficial", "Wide", "Narrow", "Long"], correct: 0 },
  { question: "Which sentence uses a semicolon correctly?", options: ["She was hungry; she ate lunch.", "She was; hungry she ate lunch.", "She; was hungry she ate lunch.", "She was hungry she ate; lunch."], correct: 0 },
  { question: "Which is a verb in the past continuous tense?", options: ["Was eating", "Eat", "Eating", "Eats"], correct: 0 },
  { question: "Which is a synonym for 'loud'?", options: ["Deafening", "Quiet", "Calm", "Peaceful"], correct: 0 },
  { question: "Which is an antonym for 'wide'?", options: ["Tight", "Broad", "Large", "Big"], correct: 0 },
  { question: "Which sentence uses a dash correctly?", options: ["She was tired – she went to bed.", "She was – tired she went to bed.", "She – was tired she went to bed.", "She was tired she went to bed –."], correct: 0 },
  { question: "Which is a verb in the future perfect tense?", options: ["Will have eaten", "Eat", "Eating", "Eats"], correct: 0 },
  { question: "Which is a synonym for 'angry'?", options: ["Incensed", "Happy", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'empty'?", options: ["Occupied", "Hollow", "Vacant", "Bare"], correct: 0 },
  { question: "Which sentence uses a comma for a list?", options: ["She bought pens, pencils, and erasers.", "She bought pens pencils and erasers.", "She bought pens and pencils and erasers.", "She bought pens, pencils and erasers."], correct: 0 },
  { question: "Which is a verb in the present continuous tense?", options: ["Is writing", "Wrote", "Writes", "Write"], correct: 0 },
  { question: "Which is a synonym for 'brave'?", options: ["Heroic", "Cowardly", "Timid", "Lazy"], correct: 0 },
  { question: "Which is an antonym for 'polite'?", options: ["Impolite", "Kind", "Helpful", "Caring"], correct: 0 },
  { question: "Which sentence is in the past perfect tense?", options: ["He had left the room.", "He left the room.", "He is leaving the room.", "He will leave the room."], correct: 0 },
  { question: "Which is a coordinating conjunction?", options: ["Or", "Although", "Because", "If"], correct: 0 },
  { question: "Which is a subordinate clause?", options: ["If it rains", "The sun shines", "She runs fast", "He is tired"], correct: 0 },
  { question: "Which is a relative clause?", options: ["Which was broken", "And then", "But she", "Quickly"], correct: 0 },
  { question: "Which is a fronted adverbial?", options: ["In the morning,", "The dog barked.", "He ran quickly.", "She is tired."], correct: 0 },
  { question: "Which sentence uses an apostrophe for omission?", options: ["Can't go there.", "The cats tail.", "The cats' tail.", "The cat tail."], correct: 0 },
  { question: "Which is a modal verb?", options: ["Might", "Run", "Dog", "Blue"], correct: 0 },
  { question: "Which is a determiner?", options: ["Each", "Quickly", "Run", "Blue"], correct: 0 },
  { question: "Which is a proper noun?", options: ["Africa", "continent", "country", "city"], correct: 0 },
  { question: "Which is a question tag?", options: ["wasn't it?", "quickly", "run", "blue"], correct: 0 },
  { question: "Which is a synonym for 'sad'?", options: ["Downcast", "Happy", "Angry", "Tired"], correct: 0 },
  { question: "Which is an antonym for 'strong'?", options: ["Delicate", "Tough", "Brave", "Bold"], correct: 0 },
  { question: "Which sentence uses a colon correctly?", options: ["She had one wish: to travel.", "She: had one wish to travel.", "She had one wish to travel:", "She had one wish: to travel"], correct: 0 },
  { question: "Which is a collective noun?", options: ["Swarm", "Dog", "Run", "Blue"], correct: 0 },
  { question: "Which is a possessive pronoun?", options: ["Ours", "We", "He", "She"], correct: 0 },
  { question: "Which is a synonym for 'fast'?", options: ["Swift", "Slow", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'difficult'?", options: ["Effortless", "Hard", "Tough", "Challenging"], correct: 0 },
  { question: "Which sentence is in the passive voice?", options: ["The window was broken by the ball.", "The ball broke the window.", "The ball is breaking the window.", "The ball will break the window."], correct: 0 },
  { question: "Which is a plural noun?", options: ["Leaves", "Leaf", "Tree", "Branch"], correct: 0 },
  { question: "Which is a compound sentence?", options: ["He was hungry, so he ate lunch.", "He was hungry because he ate lunch.", "He was hungry after he ate lunch.", "He was hungry when he ate lunch."], correct: 0 },
  { question: "Which is a synonym for 'quiet'?", options: ["Hushed", "Loud", "Noisy", "Busy"], correct: 0 },
  { question: "Which is an antonym for 'brave'?", options: ["Timid", "Strong", "Bold", "Fearless"], correct: 0 },
  { question: "Which sentence uses a comma for a list?", options: ["He saw lions, tigers, and bears.", "He saw lions tigers and bears.", "He saw lions and tigers and bears.", "He saw lions, tigers and bears."], correct: 0 },
  { question: "Which is a verb in the past tense?", options: ["Sang", "Sing", "Singing", "Sings"], correct: 0 },
  { question: "Which is a synonym for 'angry'?", options: ["Annoyed", "Happy", "Tired", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'scarce'?", options: ["Bountiful", "Rare", "Limited", "Few"], correct: 0 },
  { question: "Which sentence uses a dash correctly?", options: ["It was raining – we stayed inside.", "It was – raining we stayed inside.", "It – was raining we stayed inside.", "It was raining we stayed inside –."], correct: 0 },
  { question: "Which is a preposition of direction?", options: ["Towards", "Quickly", "Run", "Blue"], correct: 0 },
  { question: "Which is a synonym for 'tired'?", options: ["Fatigued", "Happy", "Angry", "Calm"], correct: 0 },
  { question: "Which is an antonym for 'strong'?", options: ["Fragile", "Tough", "Brave", "Bold"], correct: 0 },
  { question: "Which sentence uses a question mark correctly?", options: ["Did you finish?", "Did you finish.", "Did you finish!", "Did you finish,"], correct: 0 },
  { question: "Which is a verb in the present continuous tense?", options: ["Is reading", "Read", "Reads", "Read"], correct: 0 },
  { question: "Which is a synonym for 'happy'?", options: ["Cheerful", "Sad", "Angry", "Tired"], correct: 0 },
  { question: "Which is an antonym for 'noisy'?", options: ["Silent", "Loud", "Busy", "Calm"], correct: 0 },
  { question: "Which sentence uses an exclamation mark correctly?", options: ["Be careful!", "Be careful.", "Be careful?", "Be careful,"], correct: 0 },
  { question: "Which is a verb in the future tense?", options: ["Will write", "Write", "Wrote", "Writes"], correct: 0 },
  { question: "Which is a synonym for 'calm'?", options: ["Composed", "Loud", "Busy", "Noisy"], correct: 0 },
  { question: "Which is an antonym for 'happy'?", options: ["Unhappy", "Joyful", "Excited", "Glad"], correct: 0 },
  { question: "Which sentence uses a full stop correctly?", options: ["He sat down.", "He sat down!", "He sat down?", "He sat down,"], correct: 0 }
];